services:
  postgres:
    image: postgres:16-alpine
    container_name: pizzaria-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pizzaria
      POSTGRES_PASSWORD: pizzaria123
      POSTGRES_DB: pizzaria
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzaria -d pizzaria"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pizzaria-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pizzaria-backend
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/.env:/app/.env
    environment:
      DATABASE_URL: "postgresql://pizzaria:pizzaria123@postgres:5432/pizzaria?schema=public"
      PORT: "3333"
      CORS_ORIGIN: "http://localhost:3000"
      VAPID_PUBLIC_KEY: "BCh5az1teMFHC5QTv45MQjHxZQqdM7bo0KGJibevgPsk8FjAiHB-WYp1ITlRDVyAOq5xRUCyH51vS8CFdbV8i0Y"
      VAPID_PRIVATE_KEY: "k6RjGAzCq7wGkhv_pklKLb1kibMb1vx9ZptOZ5qXiZ4"
      VAPID_SUBJECT: "mailto:admin@pizzaria.local"
    networks:
      - pizzaria-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pizzaria-network

volumes:
  postgres_data:

networks:
  pizzaria-network:
    driver: bridge
